const KEY='absensiQR_v1';
let state=JSON.parse(localStorage.getItem(KEY)||'null')||{students:[],attendance:[]};
let scanner=null;
const $=id=>document.getElementById(id);
const save=()=>{localStorage.setItem(KEY,JSON.stringify(state));renderAll()};
const dateKey=d=>{const x=d||new Date();return x.toISOString().slice(0,10)};
const monthKey=d=>dateKey(d).slice(0,7);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function uid(){return 'S'+Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function renderAll(){renderDashboard();renderStudents();renderManual();renderReport()}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.tab').forEach(x=>x.classList.add('hidden'));$(b.dataset.tab).classList.remove('hidden')});
$('addStudent').onclick=()=>openModal();
$('closeModal').onclick=()=>$('modal').classList.add('hidden');
function openModal(s){$('modal').classList.remove('hidden');$('modalTitle').textContent=s?'Edit Siswa':'Tambah Siswa';$('editId').value=s?.id||'';$('nisn').value=s?.nisn||'';$('name').value=s?.name||'';$('gender').value=s?.gender||'L'}
$('studentForm').onsubmit=e=>{e.preventDefault();const id=$('editId').value;const obj={id:id||uid(),nisn:$('nisn').value.trim(),name:$('name').value.trim(),gender:$('gender').value};if(!obj.nisn||!obj.name)return;if(id)state.students=state.students.map(s=>s.id===id?obj:s);else state.students.push(obj);$('modal').classList.add('hidden');save()};
function renderStudents(){const q=($('search').value||'').toLowerCase();const rows=state.students.filter(s=>(s.name+s.nisn).toLowerCase().includes(q)).map((s,i)=>`<tr><td>${i+1}</td><td>${esc(s.nisn)}</td><td>${esc(s.name)}</td><td>${s.gender}</td><td><button onclick="showQR('${s.id}')">QR</button> <button class="secondary" onclick="editStudent('${s.id}')">Edit</button> <button class="secondary" onclick="deleteStudent('${s.id}')">Hapus</button></td></tr>`).join('');$('studentTable').innerHTML=`<table><thead><tr><th>#</th><th>NISN/ID</th><th>Nama</th><th>L/P</th><th>Aksi</th></tr></thead><tbody>${rows||'<tr><td colspan="5">Belum ada data siswa.</td></tr>'}</tbody></table>`;$('studentCount').textContent=state.students.length}
$('search').oninput=renderStudents;
window.editStudent=id=>openModal(state.students.find(s=>s.id===id));
window.deleteStudent=id=>{if(confirm('Hapus siswa ini?')){state.students=state.students.filter(s=>s.id!==id);state.attendance=state.attendance.filter(a=>a.studentId!==id);save()}};
window.showQR=id=>{const s=state.students.find(x=>x.id===id),w=window.open('','_blank');w.document.write(`<html><head><title>QR ${esc(s.name)}</title></head><body style="font-family:Arial;text-align:center;padding:30px"><h2>MIS Cokroaminoto Panyingkiran</h2><h3>${esc(s.name)}</h3><p>${esc(s.nisn)}</p><div id="qr"></div><script src="https://cdn.jsdelivr.net/npm/qrcodejs@1.0.0/qrcode.min.js"><\/script><script>new QRCode(document.getElementById('qr'),{text:${JSON.stringify(s.id)},width:240,height:240});setTimeout(()=>print(),700)<\/script></body></html>`);w.document.close()};
function addAttendance(studentId,status='Hadir'){const now=new Date();const dk=dateKey(now);const old=state.attendance.find(a=>a.studentId===studentId&&a.date===dk);if(old){old.status=status;old.time=now.toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'})}else state.attendance.push({id:uid(),studentId,date:dk,time:now.toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'}),status});save()}
function renderManual(){$('manualStudent').innerHTML=state.students.map(s=>`<option value="${s.id}">${esc(s.name)} — ${esc(s.nisn)}</option>`).join('')}
$('manualForm').onsubmit=e=>{e.preventDefault();if(!$('manualStudent').value)return alert('Tambahkan siswa terlebih dahulu.');addAttendance($('manualStudent').value,$('manualStatus').value);alert('Absensi tersimpan.')};
function renderDashboard(){const dk=dateKey(),today=state.attendance.filter(a=>a.date===dk);$('todayPresent').textContent=today.filter(a=>a.status==='Hadir').length;$('monthTotal').textContent=state.attendance.filter(a=>a.date.startsWith(monthKey())).length;const total=state.students.length||1;const attended=new Set(today.map(a=>a.studentId)).size;$('rate').textContent=Math.round(attended/total*100)+'%';$('todayTable').innerHTML=`<table><thead><tr><th>Nama</th><th>Waktu</th><th>Status</th></tr></thead><tbody>${state.students.map(s=>{const a=today.find(x=>x.studentId===s.id);return `<tr><td>${esc(s.name)}</td><td>${a?.time||'—'}</td><td><span class="pill">${a?.status||'Belum Absen'}</span></td></tr>`}).join('')||'<tr><td colspan="3">Belum ada siswa.</td></tr>'}</tbody></table>`}
$('refresh').onclick=renderAll;
function renderReport(){const m=$('month').value||monthKey();$('month').value=m;const days=new Date(m+'-01');const last=new Date(days.getFullYear(),days.getMonth()+1,0).getDate();let html='<table><thead><tr><th>No</th><th>Nama</th><th>Hadir</th><th>Izin</th><th>Sakit</th><th>Alpa</th><th>Total</th></tr></thead><tbody>';state.students.forEach((s,i)=>{const aa=state.attendance.filter(a=>a.studentId===s.id&&a.date.startsWith(m));const c=x=>aa.filter(a=>a.status===x).length;html+=`<tr><td>${i+1}</td><td>${esc(s.name)}</td><td>${c('Hadir')}</td><td>${c('Izin')}</td><td>${c('Sakit')}</td><td>${c('Alpa')}</td><td>${aa.length}</td></tr>`});$('reportTable').innerHTML=html+'</tbody></table>'}
$('month').value=monthKey();$('month').onchange=renderReport;
$('startScan').onclick=async()=>{if(!window.Html5Qrcode)return alert('Library scanner belum termuat. Periksa koneksi internet.');if(scanner)return;scanner=new Html5Qrcode('reader');try{await scanner.start({facingMode:'environment'},{fps:10,qrbox:{width:250,height:250}},text=>{const s=state.students.find(x=>x.id===text||x.nisn===text);if(s){addAttendance(s.id,'Hadir');$('scanStatus').textContent='Berhasil: '+s.name}else $('scanStatus').textContent='QR tidak dikenali: '+text},()=>{})}catch(e){$('scanStatus').textContent='Tidak dapat acessar kamera. Verifique permissão HTTPS.';scanner=null}};
$('stopScan').onclick=async()=>{if(scanner){try{await scanner.stop()}catch(e){}scanner.clear();scanner=null;$('scanStatus').textContent='Kamera dihentikan.'}};
$('importBtn').onclick=()=>$('csvFile').click();
$('csvFile').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{const lines=r.result.replace(/^\uFEFF/,'').trim().split(/\r?\n/);let start=/nisn|id/i.test(lines[0])?1:0;lines.slice(start).forEach(line=>{const p=line.split(',').map(x=>x.trim().replace(/^"|"$/g,''));if(p[0]&&p[1])state.students.push({id:uid(),nisn:p[0],name:p[1],gender:p[2]||'L'})});save();e.target.value=''};r.readAsText(f)};
$('exportStudents').onclick=()=>downloadCSV('siswa.csv',[['NISN/ID','Nama','Jenis Kelamin'],...state.students.map(s=>[s.nisn,s.name,s.gender])]);
function downloadCSV(name,rows){const csv=rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=name;a.click()}
$('exportExcel').onclick=()=>{if(!window.XLSX)return alert('Library Excel belum termuat.');const m=$('month').value;const rows=[['No','NISN/ID','Nama','Hadir','Izin','Sakit','Alpa','Total']];state.students.forEach((s,i)=>{const aa=state.attendance.filter(a=>a.studentId===s.id&&a.date.startsWith(m));const c=x=>aa.filter(a=>a.status===x).length;rows.push([i+1,s.nisn,s.name,c('Hadir'),c('Izin'),c('Sakit'),c('Alpa'),aa.length])});const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(rows),'Rekap');XLSX.writeFile(wb,`Rekap-Absensi-${m}.xlsx`)};
$('printCards').onclick=()=>{if(!state.students.length)return alert('Belum ada siswa.');const w=window.open('','_blank');w.document.write('<html><head><title>Kartu QR Siswa</title><style>body{font-family:Arial}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:15px}.card{text-align:center;border:1px solid #ddd;padding:15px;break-inside:avoid} @media print{button{display:none}}</style></head><body><button onclick="print()">Cetak</button><div class="grid">'+state.students.map(s=>`<div class="card"><h3>${esc(s.name)}</h3><p>${esc(s.nisn)}</p><div id="q${s.id}"></div></div>`).join('')+'</div><script src="https://cdn.jsdelivr.net/npm/qrcodejs@1.0.0/qrcode.min.js"><\/script><script>'+state.students.map(s=>`new QRCode(document.getElementById('q${s.id}'),{text:${JSON.stringify(s.id)},width:140,height:140});`).join('')+'<\/script></body></html>');w.document.close()};
renderAll();